"""Sanity tests: pipeline + validation + repair + yaml roundtrip."""
from __future__ import annotations

from app.chunking import split_chapters
from app.pipeline import run_pipeline, to_yaml_text
from app.providers.mock_provider import MockProvider
from app.repair import repair_yaml
from app.validation import validate_script
from app.yaml_io import from_yaml


NOVEL = """第一章 雨夜敲门

林屿关上诊所的灯，刚想熄掉门廊的最后一盏台灯，卷帘门外传来一阵急促的敲击声。

他犹豫了三秒，雨水正顺着门缝渗进来。

"今天已经停诊了。"他隔着门说。

门外的人没有回答，只是又敲了三下。林屿叹了口气，拉起卷帘门。

站在门外的女人浑身湿透，黑色大衣下渗出暗红色的液体。她什么也没说，径直倒进林屿怀里。

## 第二章 失忆的来客

女人醒来时，已经是第二天下午。

"你是谁？"林屿问。

"我不记得。"她盯着天花板，眼神发空。

林屿翻了翻她身上的物件——一张没写姓名的名片、一枚旧式钥匙、还有一张被水泡得模糊的合照。

"你身上有刀伤，但伤口包扎得很专业，"林屿说，"你来自一个有医疗条件的地方。"

女人闭上眼："也许吧。"

## 第三章 旧城诊所的夜晚

那一夜，诊所门外又响起雨声。

女人坐在窗边，第一次开口讲了一段话：

"我来找一个人，他三个月前从这座城市消失。"

林屿抬起头："谁？"

"我自己。"
"""


def test_split_chapters():
    chapters = split_chapters(NOVEL)
    assert len(chapters) == 3
    assert all(c.chapter_id.startswith("chapter_") for c in chapters)


def test_pipeline_e2e_mock():
    chapters = split_chapters(NOVEL)
    doc, artifacts = run_pipeline(
        chapters,
        title="雨夜来客",
        adaptation_type="short_drama",
        provider=MockProvider(),
    )
    assert doc.script.title
    assert doc.script.source.chapter_count == 3
    assert doc.script.scenes, "scenes should not be empty"
    chapter_ids = {c.chapter_id for c in chapters}
    for s in doc.script.scenes:
        assert set(s.chapter_refs) & chapter_ids
    errors = validate_script(doc.model_dump(exclude_none=True))
    assert not errors, f"unexpected errors: {errors}"


def test_yaml_roundtrip():
    chapters = split_chapters(NOVEL)
    doc, _ = run_pipeline(
        chapters, title="雨夜来客", adaptation_type="short_drama", provider=MockProvider()
    )
    y = to_yaml_text(doc)
    parsed = from_yaml(y)
    assert parsed["script"]["title"] == doc.script.title
    assert len(parsed["script"]["scenes"]) == len(doc.script.scenes)


def test_repair_recovers_unknown_speaker():
    chapters = split_chapters(NOVEL)
    doc, _ = run_pipeline(
        chapters, title="雨夜来客", adaptation_type="short_drama", provider=MockProvider()
    )
    y = to_yaml_text(doc)
    # Pick a real speaker from the first dialogue line and corrupt it
    if not doc.script.scenes or not doc.script.scenes[0].dialogue:
        import pytest

        pytest.skip("no dialogue generated by mock")
    real_speaker = doc.script.scenes[0].dialogue[0].speaker
    bad = y.replace(real_speaker, "char_typo_xxx", 1)
    fixed, changes = repair_yaml(bad)
    assert any("snapped" in c for c in changes), changes
    parsed = from_yaml(fixed)
    errs = validate_script(parsed)
    assert not errs, errs
